#!/bin/bash

echo About to process file ${1}. 

for n in $2; do
    # filename=$(basename -- ${1})
    filename=${1%.*}
    texname="${filename}-${n}.tex"
    pdfname="${filename}-${n}.pdf"
    pngname="${filename}-${n}.png"
    cp ${1} $texname
    replacestring="s/${3}/${n}/g"
    sed -i $replacestring $texname
    pdflatex $texname
    #pdflatex $texname
    pdf2png $pdfname $pngname 30%
    pdf2png $pdfname $pngname 30%
done
